// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqI7QkzA5lXBGNt1B8G8_eIgHX5qZD-Y',
    appId: '1:828992093112:web:7eaad7d97874531c026d4d',
    messagingSenderId: '828992093112',
    projectId: 'rastreabilidade-barris-2',
    authDomain: 'rastreabilidade-barris-2.firebaseapp.com',
    storageBucket: 'rastreabilidade-barris-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGm4LbTOm4aBC2_akDezg0mD1dtEfg6A',
    appId: '1:828992093112:android:84cdea97e15a6f8d026d4d',
    messagingSenderId: '828992093112',
    projectId: 'rastreabilidade-barris-2',
    storageBucket: 'rastreabilidade-barris-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTq2JQm6HBFJGTtnieuhg8TZniOAQpvw',
    appId: '1:828992093112:ios:657bedf5f6d74166026d4d',
    messagingSenderId: '828992093112',
    projectId: 'rastreabilidade-barris-2',
    storageBucket: 'rastreabilidade-barris-2.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.rastreabilidadeBarris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTq2JQm6HBFJGTtnieuhg8TZniOAQpvw',
    appId: '1:828992093112:ios:657bedf5f6d74166026d4d',
    messagingSenderId: '828992093112',
    projectId: 'rastreabilidade-barris-2',
    storageBucket: 'rastreabilidade-barris-2.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.rastreabilidadeBarris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTqI7QkzA5lXBGNt1B8G8_eIgHX5qZD-Y',
    appId: '1:828992093112:web:3c19452ac22c27d5026d4d',
    messagingSenderId: '828992093112',
    projectId: 'rastreabilidade-barris-2',
    authDomain: 'rastreabilidade-barris-2.firebaseapp.com',
    storageBucket: 'rastreabilidade-barris-2.firebasestorage.app',
  );
}
